# Generated by Django 5.1 on 2026-01-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FglFyear',
            fields=[
                ('fgl_fyear_fyid', models.CharField(db_comment='Financial aid year code.', max_length=4, primary_key=True, serialize=False)),
                ('fgl_fyear_desc', models.CharField(db_comment='Financial aid year description.', max_length=40)),
            ],
            options={
                'db_table': 'fgl_fyear',
                'db_table_comment': 'Financial aid year definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GglCount',
            fields=[
                ('ggl_count_coid', models.CharField(db_comment='Country ID, Alpha-2 code.', max_length=2, primary_key=True, serialize=False)),
                ('ggl_count_hr_name', models.CharField(db_comment='Country human-readable name.', max_length=64)),
            ],
            options={
                'db_table': 'ggl_count',
                'db_table_comment': 'Country definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GumIdent',
            fields=[
                ('gum_ident_rbid', models.CharField(db_comment='Ribbon ID.', max_length=9, primary_key=True, serialize=False)),
                ('gum_ident_first_name', models.CharField(db_comment='User first name.', max_length=32)),
                ('gum_ident_last_name', models.CharField(db_comment='User last name.', max_length=32)),
                ('gum_ident_middle_name', models.CharField(blank=True, db_comment='User middle name.', max_length=32, null=True)),
                ('gum_ident_birthday', models.DateField(blank=True, db_comment='User birth date.', null=True)),
                ('gum_ident_idnum', models.CharField(blank=True, db_comment='User national identification number.', max_length=32, null=True)),
                ('gum_ident_created_date', models.DateField(db_comment='Date record was created.')),
                ('gum_ident_activity_date', models.DateField(blank=True, db_comment='Date record was last modified.', null=True)),
                ('gum_ident_modified_by', models.CharField(blank=True, db_comment='User who last modified record.', max_length=40, null=True)),
            ],
            options={
                'db_table': 'gum_ident',
                'db_table_comment': 'Person identity base record table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SclCipcd',
            fields=[
                ('scl_cipcd_ciid', models.CharField(db_comment='CIP code ID in NCES format (2, 4, or 6 digit structure).', max_length=7, primary_key=True, serialize=False)),
                ('scl_cipcd_hr_name', models.CharField(db_comment='CIP code human-readable name.', max_length=50)),
                ('scl_cipcd_cal_sp04_code', models.CharField(blank=True, db_comment='SP04 reporting code for the CIP classification.', max_length=5, null=True)),
                ('scl_cipcd_publish_date', models.DateField(blank=True, db_comment='Date the CIP code was published.', null=True)),
            ],
            options={
                'db_table': 'scl_cipcd',
                'db_table_comment': 'CIP code definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SclDegrs',
            fields=[
                ('scl_degrs_dgid', models.CharField(db_comment='Degree ID.', max_length=6, primary_key=True, serialize=False)),
                ('scl_degrs_hr_name', models.CharField(db_comment='Degree human-readable name.', max_length=32)),
                ('scl_degrs_finaid_ind', models.CharField(blank=True, db_comment='Degree financial aid indicator.', max_length=1, null=True)),
            ],
            options={
                'db_table': 'scl_degrs',
                'db_table_comment': 'Degree lookup table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SclDlevl',
            fields=[
                ('scl_dlevl_dlid', models.CharField(db_comment='Degree level ID.', max_length=4, primary_key=True, serialize=False)),
                ('scl_dlevl_hr_name', models.CharField(db_comment='Degree level human-readable name.', max_length=32)),
                ('scl_dlevl_nslds_equiv', models.CharField(blank=True, db_comment='Degree level National Student Loan Data System category code.', max_length=1, null=True)),
                ('scl_dlevl_eqf_equiv', models.CharField(blank=True, db_comment='European Qualifications Framework equivalency.', max_length=1, null=True)),
            ],
            options={
                'db_table': 'scl_dlevl',
                'db_table_comment': 'Degree level lookup table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SclMajor',
            fields=[
                ('scl_major_mrid', models.CharField(db_comment='Major ID.', max_length=8, primary_key=True, serialize=False)),
                ('scl_major_hr_name', models.CharField(db_comment='Major title.', max_length=32)),
                ('scl_major_short_name', models.CharField(db_comment='Major short name.', max_length=12)),
                ('scl_major_major_ind', models.CharField(db_comment='Valid major indicator.', max_length=1)),
                ('scl_major_minor_ind', models.CharField(db_comment='Valid minor indicator.', max_length=1)),
            ],
            options={
                'db_table': 'scl_major',
                'db_table_comment': 'Major report table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SdlColeg',
            fields=[
                ('sdl_coleg_cgid', models.CharField(db_comment='College ID.', max_length=4, primary_key=True, serialize=False)),
                ('sdl_coleg_hr_name', models.CharField(db_comment='College human-readable name.', max_length=32)),
                ('sdl_coleg_short_name', models.CharField(db_comment='College short name.', max_length=12)),
            ],
            options={
                'db_table': 'sdl_coleg',
                'db_table_comment': 'College/school definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SdlDepts',
            fields=[
                ('sdl_depts_dpid', models.CharField(db_comment='Department ID.', max_length=4, primary_key=True, serialize=False)),
                ('sdl_depts_hr_name', models.CharField(db_comment='Department human-readable name.', max_length=32)),
            ],
            options={
                'db_table': 'sdl_depts',
                'db_table_comment': 'Academic department lookup table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SglLevel',
            fields=[
                ('sgl_level_lvid', models.CharField(db_comment='Level ID.', max_length=2, primary_key=True, serialize=False)),
                ('sgl_level_hr_name', models.CharField(db_comment='Level human-readable name.', max_length=32)),
                ('sgl_level_degree_ind', models.CharField(db_comment='Degree-seeking indicator.', max_length=1)),
            ],
            options={
                'db_table': 'sgl_level',
                'db_table_comment': 'Student level lookup table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SglSmstr',
            fields=[
                ('sgl_smstr_smid', models.CharField(db_comment='Semester ID.', max_length=4, primary_key=True, serialize=False)),
                ('sgl_smstr_hr_name', models.CharField(db_comment='Semester human-readable name.', max_length=6)),
            ],
            options={
                'db_table': 'sgl_smstr',
                'db_table_comment': 'Semester definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SglStype',
            fields=[
                ('sgl_stype_stid', models.CharField(db_comment='Student type ID.', max_length=2, primary_key=True, serialize=False)),
                ('sgl_stype_hr_name', models.CharField(db_comment='Student type human-readable name.', max_length=32)),
            ],
            options={
                'db_table': 'sgl_stype',
                'db_table_comment': 'Student type lookup table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SglTerms',
            fields=[
                ('sgl_terms_tmid', models.CharField(db_comment='Term ID. Format: YYYY + semester code (1S = Summer, 2F = Fall, 3W = Winter).', max_length=6, primary_key=True, serialize=False)),
                ('sgl_terms_year', models.IntegerField(db_comment='Calendar year of the term.')),
                ('sgl_terms_fyid', models.CharField(db_comment='Financial aid year code.', max_length=4)),
                ('sgl_terms_start_date', models.DateField(db_comment='Term official start date.')),
                ('sgl_terms_end_date', models.DateField(db_comment='Term official end date.')),
            ],
            options={
                'db_table': 'sgl_terms',
                'db_table_comment': 'Academic term definition table.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrbSects',
            fields=[
                ('srb_sects_scid', models.IntegerField(primary_key=True, serialize=False)),
                ('srb_sects_section_seq', models.IntegerField(blank=True, db_comment='Section Sequence Number', null=True)),
                ('srb_sects_prim_inst', models.CharField(blank=True, db_comment='Primary Instructor', max_length=9, null=True)),
                ('srb_sects_scnd_inst', models.CharField(blank=True, db_comment='Secondary Instructor', max_length=9, null=True)),
            ],
            options={
                'db_table': 'srb_sects',
                'db_table_comment': 'Section bridge table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrhEnrol',
            fields=[
                ('srh_enrol_rbid', models.CharField(db_comment='Ribbon ID', max_length=9, primary_key=True, serialize=False)),
                ('srh_enrol_created_date', models.DateField(db_comment='Date record was created.')),
                ('srh_enrol_activity_date', models.DateField(db_comment='Date record was last modified.')),
                ('srh_enrol_modified_by', models.CharField(db_comment='User who last modified record.', max_length=40)),
            ],
            options={
                'db_table': 'srh_enrol',
                'db_table_comment': 'Registration Status History Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrlCours',
            fields=[
                ('srl_cours_crid', models.CharField(db_comment='Course ID', max_length=6, primary_key=True, serialize=False)),
                ('srl_cours_crse_num', models.CharField(db_comment='Course Number', max_length=6)),
                ('srl_cours_hr_name', models.CharField(db_comment='Course Title', max_length=64)),
                ('srl_cours_inactive_ind', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'srl_cours',
                'db_table_comment': 'Course lookup table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrlEnrst',
            fields=[
                ('srl_enrst_esid', models.CharField(db_comment='Enrollment Status ID', max_length=2, primary_key=True, serialize=False)),
                ('srl_enrst_hr_name', models.CharField(db_comment='Enrollment Status Human Readable Name', max_length=32)),
                ('srl_enrst_roll_ind', models.CharField(db_comment='Indicates if student is enrolled in the course (Y/N).', max_length=1)),
                ('srl_enrst_credit_ind', models.CharField(db_comment='Indicates if student receives credit for the course (Y/N).', max_length=1)),
            ],
            options={
                'db_table': 'srl_enrst',
                'db_table_comment': 'Enrollment Status Lookup Table with Predefined Values. \n     Combines roll and credit flags to indicate enrollment semantics:\n     - Y,Y = Normal registration (Registered, Web Registered, Admin Registered, Vendor Registered)\n     - N,N = Withdrawal (Withdraw, Web Withdraw, Admin Withdraw, Vendor Withdraw)\n     - N,Y = Special cases (Credited Withdraw, Transfer Course, Honorary Course)\n     - Y,N = Audit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SrlSubjs',
            fields=[
                ('srl_subjs_sbid', models.CharField(db_comment='Subject ID', max_length=4, primary_key=True, serialize=False)),
                ('srl_subjs_hr_name', models.CharField(blank=True, db_comment='Subject Human Readable Name', max_length=64, null=True)),
            ],
            options={
                'db_table': 'srl_subjs',
                'db_table_comment': 'Course Subject Report Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgmStubi',
            fields=[
                ('sgm_stubi_rbid', models.ForeignKey(db_column='sgm_stubi_rbid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stubi_records', serialize=False, to='sis.gumident')),
                ('sgm_stubi_active_ind', models.CharField(max_length=1)),
                ('sgm_stubi_created_date', models.DateField(db_comment='Record creation date.')),
                ('sgm_stubi_activity_date', models.DateField(blank=True, db_comment='Record last modification date.', null=True)),
                ('sgm_stubi_modified_by', models.CharField(blank=True, db_comment='User who last modified the record.', max_length=40, null=True)),
            ],
            options={
                'db_table': 'sgm_stubi',
                'db_table_comment': 'Student base information table.',
                'managed': False,
            },
        ),
    ]
